version: '3'
services: 
  frontend:
    container_name: sun-frontend
    build: ./frontend
    environment:
      - NODE_ENV=development
    tty: true
    stdin_open: true
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c 'yarn install &&
     yarn add @chakra-ui/react @emotion/react@^11 @emotion/styled@^11 framer-motion@^4 &&
     yarn add react-router-dom@6 &&
     yarn dev'
  

