version: '3'
services: 
  # frontend
  frontend:
    container_name: sun-frontend
    build: ./frontend
    environment:
      - NODE_ENV=development
    tty: true
    stdin_open: true
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/sun-app
    command: sh -c 'yarn install && yarn dev'
    networks:
      - sun-app-network
  # backend
  backend:
    container_name: sun-backend
    build: ./backend
    environment:
      - ENV=local
    tty: true
    stdin_open: true
    ports:
      - 8888:8888
    volumes:
      - ./backend:/sun-app
    networks:
      - sun-app-network

networks:
  sun-app-network:
    driver: bridge